services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: ewlarson/ogm-api:0.1.1
    container_name: ogm-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@paradedb:5432/geoblacklight_development
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_INDEX=geoblacklight
      - LOG_PATH=/app/logs
      - APPLICATION_URL=http://localhost:8000
      - CORS_ORIGINS=http://localhost:5173,https://ewlarson.github.io,https://data-api.ngrok.io
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=604800  # 7 days in seconds
    ports:
      - "8000:8000"
    depends_on:
      elasticsearch:
        condition: service_healthy
      paradedb:
        condition: service_started
      redis:
        condition: service_started
    volumes:
      - ./logs:/app/logs
      - .:/app
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: data-api-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5

  paradedb:
    image: paradedb/paradedb:latest
    container_name: data-api-paradedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=geoblacklight_development
    ports:
      - "2345:5432"
    volumes:
      - paradedb-data:/var/lib/postgresql/data
    networks:
      - elastic

  redis:
    image: redis:7.2
    container_name: data-api-redis
    command: redis-server --appendonly yes  # Enable persistence
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.worker worker --loglevel=INFO
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_TTL=604800
      - PYTHONUNBUFFERED=1  # Important for logging
    volumes:
      - ./logs:/app/logs
      - .:/app  # Mount code for development
    depends_on:
      - redis
    networks:
      - elastic

  flower:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A app.tasks.worker flower --port=5555
    ports:
      - "5555:5555"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - celery_worker
    networks:
      - elastic

volumes:
  elasticsearch-data:
  paradedb-data:
  redis-data:  # Add Redis volume

networks:
  elastic:
    driver: bridge 